apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::094232465309:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1O7II5Q6XMQWW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::094232465309:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-06T02:10:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1424"
  uid: 1ee3c0ed-3533-4be4-ad4a-45d9085060e3
